name: Build & Deploy Pages (RSS → HTML + sitemap)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"   # 6시간마다
#    - cron: "0 * * * 1"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install feedparser requests

      - name: Build static site from RSS
        env:
          BASE_URL: https://dorun092.github.io
          RSS_URL: https://rss.blog.naver.com/do_run_.xml
          SITE_TITLE: "네이버 블로그 최신 글"
          SITE_DESC: "네이버 블로그 최신 글 모음 (자동 갱신)"
          SITE_META: '<meta name="google-site-verification" content="UevNLqf1T48vR6HMj35XBh-kLv_5gSru1_Un9WTym3E" />'
          MAX_ITEMS: "40"
        run: python scripts/build_rss.py

      - name: Make script executable
        run: chmod +x scripts/post_blogger.py

      - name: Run blogger poster
        env:
          GCP_CLIENT_ID: ${{ secrets.GCP_CLIENT_ID }}
          GCP_CLIENT_SECRET: ${{ secrets.GCP_CLIENT_SECRET }}
          GCP_REFRESH_TOKEN: ${{ secrets.GCP_REFRESH_TOKEN }}
          BLOG_ID: "580830179711521471"
          RSS_URL: "https://rss.blog.naver.com/do_run_.xml"
          MAX_POSTS: "1"
        run: scripts/post_blogger.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4